---

- hosts:
    - webhook_site
  collections:
    - rockaut.conntest
  gather_facts: no
  tasks:
    - name: lets try 
      rockaut.conntest.webhook_site:
        path: /fd09b73b-9379-4025-bbc7-96548380c4db
        data: >-
          {
            "whatever": "it takes!"
          }
    - name: lets try 2
      rockaut.conntest.webhook_site:
        path: /fd09b73b-9379-4025-bbc7-96548380c4db
        data: |-
          {
            "whatever": "it takes!"
          }
