---

- hosts:
    - webhook_site
  collections:
    - rockaut.conntest
    - ansible.netcommon
  gather_facts: no
  vars:
    whpath: "/d9828949-ac62-4a7a-9182-087da824e2c0"
  tasks:
    - name: lets try 
      rockaut.conntest.webhook_site:
        path: "{{ whpath }}"
        data: >-
          {
            "whatever": "it takes!"
          }
